spring.application.name=MHC

jwt.secret=64fb789a858cbb6a0e94b70cd8dffda53242c4d0dbd5da57f267a8a29edf6184
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

spring.datasource.url=jdbc:sqlserver://QUANGHUY\\QHUY:1433;databaseName=MHC;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect